_BASE_: "diffusion.yaml"

####################################### DATASETS #######################################
DATASETS:
  TRAIN: 'MSCoCoDiffusionKDDataset'

###################################### DATALOADER ######################################
DATALOADER:
  TRAIN_BATCH_SIZE: 128
  SEQ_PER_SAMPLE: 5

  KD_PRED_FILE: "/home/jinyuda/dataset/xmodaler/mscoco/autoregressive_teacher_pred_ep25.pkl"
  USE_KD_TOKENS_AS_INPUT: True

######################################### Engine #########################################
ENGINE:
  NAME: 'RLDiffusionTrainer'

######################################### MODEL #########################################
MODEL:
  WEIGHTS: "/home/jinyuda/Try/SCD-Net-main/output/stage1/rl/model_Epoch_00006_Iter_0005309.pth"

####################################### Optimizer #######################################
SOLVER:
  NAME: 'Adam'
  EPOCH: 60
  BASE_LR: 0.00001

####################################### lr scheduler ####################################### 
LR_SCHEDULER:
  NAME: 'FixLR'

####################################### losses ####################################### 
LOSSES:
  NAMES: []