_BASE_: "rrg_ce_eos.yaml"
####################################### DATASETS #######################################
DATASETS:
  TRAIN: 'RRGDiffusionDataset'
  VAL: ''
  TEST: 'RRGDiffusionDataset'
OUTPUT_DIR: './rrg_output/stage1/mimic_ce_eos_rl'
###################################### DATALOADER ######################################
DATALOADER:
  TRAIN_BATCH_SIZE: 128
  TEST_BATCH_SIZE: 128
  NUM_WORKERS: 12
  ANNO_FOLDER: "/home/jinyuda/dataset/medic/mimic_cxr/pkl/mimic_gts.pkl"
  SEQ_PER_SAMPLE: 3
  IMAGE_PATH: '/home/jinyuda/dataset/medic/mimic_cxr/images/'
  SIMILAR_PATH: "/home/jinyuda/dataset/medic/mimic_cxr/pkl/mim_whole_bert.npy"

######################################### Engine #########################################
ENGINE:
  NAME: 'RLDiffusionTrainer'

######################################### MODEL #########################################
MODEL:

  WEIGHTS: "/home/jinyuda/Try/SCD-Net-main/rrg_output/stage1/mimic_ce_eos/model_Epoch_00013_Iter_0027494.pth"

####################################### Optimizer #######################################
SOLVER:
  NAME: 'Adam'
  EPOCH: 60
  BASE_LR: 0.00001  # 0.00001


####################################### lr scheduler ####################################### 
LR_SCHEDULER:
  NAME: 'FixLR'

####################################### losses #######################################


####################################### scorer ####################################### 
SCORER:
  NAME: 'Bleu4Scorer'
  TYPES: [ 'Bleu-4' ]
  WEIGHTS: [ 1.0 ]
  GT_PATH: "/home/jinyuda/dataset/medic/mimic_cxr/pkl/mimic_id2gtid.pkl"
#  CIDER_CACHED: '/home/jinyuda/dataset/xmodaler/mscoco/mscoco_train_cider.pkl'
  EOS_ID: 0


